apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fe-demo-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev

replicas:
  - name: fe-demo-deployment
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.localhost
      - op: remove
        path: /spec/rules/1
    target:
      kind: Ingress
      name: fe-demo-ingress
