apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fe-demo-uat

resources:
  - ../../base

namePrefix: uat-

labels:
  - pairs:
      environment: uat

replicas:
  - name: fe-demo-deployment
    count: 2

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: uat.localhost
      - op: remove
        path: /spec/rules/1
    target:
      kind: Ingress
      name: fe-demo-ingress
